# Site Settings
title: Beibei Zhang
title2: Free Mortgage Calculator
description: Free Mortgage Calculator
url: https://beibeizhang22.github.io
baseurl: "" # Leave blank for root-level site

# Remote Theme
remote_theme: pages-themes/cayman # Cayman theme repository

# Plugins
plugins:
  - jekyll-remote-theme # Enables remote themes
  - jekyll-sitemap

# Optional: Additional Settings
markdown: kramdown
footer: false

